// Generated by Wrangler on Sun Jun 30 2024 22:50:30 GMT+0800 (China Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
    pastebin: KVNamespace
    TURNSTILE_SITEKEY: string
    TURNSTILE_SECRETKEY: string
}
