
// 64kB
export const CONTENT_MAX_SIZE = 64 * 1024
export const FILENAME_MAX_SIZE = 256

// common file extension to language map for prism
// https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/AVAILABLE_LANGUAGES_PRISM.MD
export const FILE_EXT_TO_LANGUAGE: { [key: string]: string } = {
  'as': 'actionscript',
  aspx: 'aspnet',
  ahk: 'autohotkey',
  sh: 'bash',
  bas: 'basic',
  y: 'bison',
  bf: 'brainfuck',
  c: 'c',
  clj: 'clojure',
  cmake: 'cmake',
  cbl: 'cobol',
  cob: 'cobol',
  coffee: 'coffeescript',
  cpp: 'cpp',
  cs: 'csharp',
  css: 'css',
  csv: 'csv',
  d: 'd',
  dart: 'dart',
  diff: 'diff',
  editorconfig: 'editorconfig',
  ejs: 'ejs',
  ex: 'elixir',
  erb: 'erb',
  erl: 'erlang',
  f: 'fortran',
  f90: 'fortran',
  go: 'go',
  graphql: 'graphql',
  gql: 'graphql',
  haml: 'haml',
  hbs: 'handlebars',
  hs: 'haskell',
  lhs: 'haskell',
  ini: 'ini',
  java: 'java',
  js: 'javascript',
  json: 'json',
  jsx: 'jsx',
  jl: 'julia',
  less: 'less',
  liquid: 'liquid',
  lsp: 'lisp',
  log: 'log',
  lua: 'lua',
  md: 'markdown',
  nix: 'nix',
  m: 'objectivec',
  pas: 'pascal',
  pl: 'perl',
  php: 'php',
  ps1: 'powershell',
  proto: 'protobuf',
  pug: 'pug',
  py: 'python',
  r: 'r',
  rb: 'ruby',
  rs: 'rust',
  sass: 'sass',
  scala: 'scala',
  sc: 'scala',
  scss: 'scss',
  st: 'smalltalk',
  sol: 'solidity',
  sql: 'sql',
  styl: 'stylus',
  swift: 'swift',
  tcl: 'tcl',
  toml: 'toml',
  tsx: 'tsx',
  ts: 'typescript',
  vim: 'vim',
  vlg: 'verilog',
  vh: 'verilog',
  vb: 'visual-basic',
  wasm: 'wasm',
  wiki: 'wiki',
  yaml: 'yaml',
  conf: 'ini',
  html: 'markup',
  xml: 'markup',
  svg: 'markup',
}

export const LANGUAGES = new Set(Object.values(FILE_EXT_TO_LANGUAGE))

export const EXACT_FILENAME_LANGUAGE: { [key: string]: string } = {
  Dockerfile: 'docker',
  Makefile: 'makefile',
}